import { Pergunta } from '@/types/diagnostico'

export const perguntasDiretoria: Pergunta[] = [
  // === SEÇÃO A: CONTEXTO DA EMPRESA ===
  {
    id: 'dir_segmento',
    texto: 'Qual é o segmento principal da empresa?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Contexto da Empresa',
    opcoes: [
      { label: 'Serviços profissionais (consultoria, advocacia, contabilidade)', value: 'servicos_profissionais' },
      { label: 'Comércio (varejo/atacado)', value: 'comercio' },
      { label: 'Indústria/Manufatura', value: 'industria' },
      { label: 'Saúde (clínicas, laboratórios)', value: 'saude' },
      { label: 'Educação', value: 'educacao' },
      { label: 'Construção civil / Engenharia', value: 'construcao' },
      { label: 'Tecnologia', value: 'tecnologia' },
      { label: 'Outro', value: 'outro' },
    ],
  },
  {
    id: 'dir_funcionarios',
    texto: 'Quantos funcionários a empresa possui hoje?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Contexto da Empresa',
    opcoes: [
      { label: '1 a 10', value: '1-10' },
      { label: '11 a 30', value: '11-30' },
      { label: '31 a 100', value: '31-100' },
      { label: '101 a 300', value: '101-300' },
      { label: 'Mais de 300', value: '300+' },
    ],
  },
  {
    id: 'dir_momento',
    texto: 'A empresa está em qual momento?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Contexto da Empresa',
    dicaConsultor: '"Crescimento" e "Escala" indicam urgência alta para automações. "Estabilização" = terreno fértil para quick wins.',
    opcoes: [
      { label: 'Sobrevivência — focada em manter as portas abertas', value: 'sobrevivencia' },
      { label: 'Estabilização — funciona, mas com muitos processos manuais', value: 'estabilizacao' },
      { label: 'Crescimento — ganhando clientes mas a operação não acompanha', value: 'crescimento' },
      { label: 'Escala — precisa de sistemas para crescer sem aumentar custo', value: 'escala' },
    ],
  },

  // === SEÇÃO B: VISIBILIDADE E DECISÃO ===
  {
    id: 'dir_acesso_dados',
    texto: 'Quando você precisa de um número importante (faturamento, inadimplência, status de projetos), como consegue essa informação?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Visibilidade e Decisão',
    dicaConsultor: 'Qualquer resposta que não seja a primeira = oportunidade para dashboards e relatórios automáticos.',
    opcoes: [
      { label: 'Tenho um painel/dashboard que consulto em tempo real', value: 'dashboard_tempo_real' },
      { label: 'Peço para alguém montar um relatório (leva horas)', value: 'relatorio_horas' },
      { label: 'Peço para alguém montar um relatório (leva dias)', value: 'relatorio_dias' },
      { label: 'Consulto planilhas que nem sempre estão atualizadas', value: 'planilhas_desatualizadas' },
      { label: 'Sinceramente, muitas vezes decido sem ter os dados', value: 'sem_dados' },
    ],
  },
  {
    id: 'dir_info_segunda',
    texto: 'Quais informações você gostaria de ver toda segunda-feira de manhã, mas hoje não tem acesso fácil?',
    tipo: 'multiple',
    obrigatoria: true,
    secao: 'Visibilidade e Decisão',
    dicaConsultor: 'Cada item marcado = um módulo de dashboard.',
    opcoes: [
      { label: 'Faturamento da semana/mês', value: 'faturamento' },
      { label: 'Inadimplência e contas a receber', value: 'inadimplencia' },
      { label: 'Status dos projetos/pedidos em andamento', value: 'status_projetos' },
      { label: 'Satisfação dos clientes', value: 'satisfacao_clientes' },
      { label: 'Produtividade da equipe', value: 'produtividade' },
      { label: 'Pipeline comercial (oportunidades em aberto)', value: 'pipeline' },
    ],
  },
  {
    id: 'dir_decisao_errada',
    texto: 'Você já tomou uma decisão importante baseada em informação que depois descobriu estar errada ou desatualizada?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Visibilidade e Decisão',
    dicaConsultor: '"Sim" ou "Não tenho como saber" = alta urgência para centralização de dados.',
    opcoes: [
      { label: 'Sim, mais de uma vez', value: 'sim_varias' },
      { label: 'Sim, pelo menos uma vez', value: 'sim_uma' },
      { label: 'Não que eu me lembre', value: 'nao' },
      { label: 'Não tenho como saber — esse é o problema', value: 'nao_sei' },
    ],
  },

  // === SEÇÃO C: GARGALOS E CRESCIMENTO ===
  {
    id: 'dir_dobrar',
    texto: 'Se a empresa dobrasse de tamanho nos próximos 12 meses, o que quebraria primeiro?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Gargalos e Crescimento',
    dicaConsultor: 'A resposta aponta diretamente para o departamento que precisa de solução primeiro.',
    opcoes: [
      { label: 'O financeiro não daria conta de processar tudo', value: 'financeiro' },
      { label: 'A equipe operacional ficaria sobrecarregada', value: 'operacional' },
      { label: 'O atendimento ao cliente perderia qualidade', value: 'atendimento' },
      { label: 'A comunicação interna viraria um caos', value: 'comunicacao' },
      { label: 'Os sistemas atuais não aguentariam', value: 'sistemas' },
      { label: 'Não sei dizer — e isso me preocupa', value: 'nao_sei' },
    ],
  },
  {
    id: 'dir_oferta_limitada',
    texto: 'Existe algo que a empresa gostaria de oferecer ao cliente mas não consegue porque dá trabalho demais?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Gargalos e Crescimento',
    dicaConsultor: 'Cada "Sim" = receita perdida que pode ser recuperada com automação. ROI direto.',
    opcoes: [
      { label: 'Sim — relatórios ou acompanhamento em tempo real para o cliente', value: 'sim_relatorios' },
      { label: 'Sim — atendimento mais rápido ou disponível fora do horário', value: 'sim_atendimento' },
      { label: 'Sim — um portal onde o cliente resolve coisas sozinho', value: 'sim_portal' },
      { label: 'Sim — outro', value: 'sim_outro' },
      { label: 'Não, conseguimos entregar tudo que queremos', value: 'nao' },
    ],
  },
  {
    id: 'dir_desperdicio',
    texto: 'Qual é o maior "desperdício" que você enxerga na empresa hoje?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Gargalos e Crescimento',
    opcoes: [
      { label: 'Tempo da equipe gasto em tarefas repetitivas', value: 'tempo_repetitivo' },
      { label: 'Retrabalho por falha de comunicação', value: 'retrabalho' },
      { label: 'Dinheiro gasto em ferramentas que ninguém usa direito', value: 'ferramentas_inuteis' },
      { label: 'Oportunidades de venda perdidas por falta de follow-up', value: 'vendas_perdidas' },
      { label: 'Conhecimento que se perde quando alguém sai da empresa', value: 'conhecimento_perdido' },
    ],
  },

  // === SEÇÃO D: TECNOLOGIA E INVESTIMENTO ===
  {
    id: 'dir_ferramentas',
    texto: 'Quais ferramentas a empresa usa hoje?',
    tipo: 'multiple',
    obrigatoria: true,
    secao: 'Tecnologia e Investimento',
    dicaConsultor: '"Planilhas como sistema principal" + "WhatsApp" = cenário ideal para AIOS.',
    opcoes: [
      { label: 'Planilhas (Excel/Google Sheets) como sistema principal', value: 'planilhas' },
      { label: 'ERP (SAP, TOTVS, Bling, Omie, outro)', value: 'erp' },
      { label: 'CRM (Salesforce, Pipedrive, HubSpot, outro)', value: 'crm' },
      { label: 'WhatsApp como canal principal de trabalho', value: 'whatsapp' },
      { label: 'E-mail como canal principal de trabalho', value: 'email' },
      { label: 'Sistemas próprios/legados', value: 'legado' },
      { label: 'Quase nada — a maior parte é manual', value: 'manual' },
    ],
  },
  {
    id: 'dir_software_falhou',
    texto: 'Vocês já contrataram alguma solução de software que não deu certo? Qual foi o principal motivo?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Tecnologia e Investimento',
    dicaConsultor: 'Essas respostas definem como apresentar a proposta. Se "complexo demais" aparece, enfatizar simplicidade.',
    opcoes: [
      { label: 'Era caro demais para o que entregava', value: 'caro' },
      { label: 'Era complexo demais — ninguém usou', value: 'complexo' },
      { label: 'Não se adaptava ao nosso processo', value: 'inflexivel' },
      { label: 'O suporte era ruim', value: 'suporte_ruim' },
      { label: 'Nunca contratamos nada assim', value: 'nunca' },
    ],
  },
  {
    id: 'dir_investimento',
    texto: 'Se existisse UMA solução que resolvesse o maior problema da sua operação, quanto a empresa estaria disposta a investir mensalmente?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Tecnologia e Investimento',
    dicaConsultor: 'Define o escopo da proposta. "Depende do retorno" = precisa de business case com ROI.',
    opcoes: [
      { label: 'Até R$ 500/mês', value: 'ate_500' },
      { label: 'Entre R$ 500 e R$ 2.000/mês', value: '500_2000' },
      { label: 'Entre R$ 2.000 e R$ 5.000/mês', value: '2000_5000' },
      { label: 'Acima de R$ 5.000/mês', value: 'acima_5000' },
      { label: 'Depende do retorno comprovado', value: 'depende_roi' },
    ],
  },
  {
    id: 'dir_dor_principal',
    texto: 'Em uma frase, qual é o problema que mais tira seu sono na empresa hoje?',
    tipo: 'text',
    obrigatoria: true,
    secao: 'Tecnologia e Investimento',
    dicaConsultor: 'Essa é a frase que abre a proposta comercial. "Você nos disse que ___. É exatamente isso que vamos resolver."',
  },
]
