import { Pergunta } from '@/types/diagnostico'

export const perguntasEquipe: Pergunta[] = [
  // === SEÇÃO A: SEU DIA A DIA ===
  {
    id: 'eq_area',
    texto: 'Qual é a sua área principal?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Seu Dia a Dia',
    opcoes: [
      { label: 'Administrativo / Financeiro', value: 'administrativo' },
      { label: 'Comercial / Vendas', value: 'comercial' },
      { label: 'Operações / Produção', value: 'operacoes' },
      { label: 'Atendimento ao Cliente / Suporte', value: 'atendimento' },
      { label: 'RH / Departamento Pessoal', value: 'rh' },
      { label: 'TI', value: 'ti' },
      { label: 'Outro', value: 'outro' },
    ],
  },
  {
    id: 'eq_tempo_repetitivo',
    texto: 'Quanto do seu dia é gasto em tarefas repetitivas que poderiam ser automatizadas?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Seu Dia a Dia',
    dicaConsultor: '50%+ = candidato prioritário para automação. Multiplicar pelo salário = custo do desperdício.',
    opcoes: [
      { label: 'Quase nada — meu trabalho é bem variado', value: 'quase_nada' },
      { label: 'Cerca de 25% — algumas coisas se repetem', value: '25_porcento' },
      { label: 'Cerca de 50% — metade do meu dia é repetitivo', value: '50_porcento' },
      { label: 'Mais de 50% — a maior parte é sempre a mesma coisa', value: 'mais_50' },
    ],
  },
  {
    id: 'eq_tarefas_frequentes',
    texto: 'Quais dessas tarefas você faz com frequência?',
    tipo: 'multiple',
    obrigatoria: true,
    secao: 'Seu Dia a Dia',
    dicaConsultor: 'Cada item é uma micro-automação. Esse mapa define o backlog de soluções.',
    opcoes: [
      { label: 'Preencher planilhas manualmente', value: 'planilhas_manual' },
      { label: 'Copiar informação de um sistema para outro', value: 'copiar_sistemas' },
      { label: 'Enviar e-mails ou mensagens de acompanhamento repetitivas', value: 'emails_repetitivos' },
      { label: 'Gerar relatórios que poderiam ser automáticos', value: 'relatorios_manuais' },
      { label: 'Buscar informações em vários lugares para responder uma pergunta simples', value: 'buscar_info' },
      { label: 'Cobrar colegas sobre status de tarefas', value: 'cobrar_status' },
      { label: 'Formatar documentos (propostas, contratos, relatórios)', value: 'formatar_docs' },
      { label: 'Fazer cálculos que poderiam ser automatizados', value: 'calculos_manuais' },
    ],
  },
  {
    id: 'eq_frustracao',
    texto: 'Qual dessas frases descreve melhor uma frustração sua no trabalho?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Seu Dia a Dia',
    dicaConsultor: 'Cada resposta aponta para um tipo de solução específica.',
    opcoes: [
      { label: '"Eu passo mais tempo procurando informação do que usando ela"', value: 'procurando_info' },
      { label: '"Eu faço o mesmo trabalho várias vezes porque a informação se perde"', value: 'retrabalho' },
      { label: '"Eu dependo de outras pessoas para conseguir fazer meu trabalho"', value: 'dependencia' },
      { label: '"Eu sei que tem um jeito melhor, mas ninguém tem tempo de mudar"', value: 'sem_tempo_mudar' },
      { label: '"Eu não tenho frustração relevante com os processos atuais"', value: 'sem_frustracao' },
    ],
  },

  // === SEÇÃO B: FERRAMENTAS E COMUNICAÇÃO ===
  {
    id: 'eq_onde_info',
    texto: 'Onde fica a informação que você mais precisa no dia a dia?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    dicaConsultor: '"Cabeça de um colega" e "WhatsApp" = urgência para base de conhecimento centralizada.',
    opcoes: [
      { label: 'Na cabeça de um colega — preciso perguntar', value: 'cabeca_colega' },
      { label: 'Em planilhas compartilhadas', value: 'planilhas' },
      { label: 'Em conversas de WhatsApp/e-mail', value: 'whatsapp_email' },
      { label: 'Em um sistema da empresa', value: 'sistema' },
      { label: 'Em vários lugares diferentes — depende do que procuro', value: 'varios_lugares' },
    ],
  },
  {
    id: 'eq_duvida_processo',
    texto: 'Quando você tem uma dúvida sobre um processo da empresa, o que faz?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    dicaConsultor: '"Pergunto para colega" = dependência de pessoas. Oportunidade para portal de conhecimento.',
    opcoes: [
      { label: 'Pergunto para um colega', value: 'pergunta_colega' },
      { label: 'Procuro em um documento/manual', value: 'documento' },
      { label: 'Tento resolver sozinho na tentativa e erro', value: 'tentativa_erro' },
      { label: 'Mando mensagem no grupo de WhatsApp', value: 'whatsapp' },
    ],
  },
  {
    id: 'eq_retrabalho',
    texto: 'Com que frequência acontece de você descobrir que outra pessoa já fez (ou está fazendo) o mesmo trabalho que você?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    dicaConsultor: '"Toda semana" = retrabalho sistêmico. Precisa de kanban ou sistema de atribuição de tarefas.',
    opcoes: [
      { label: 'Toda semana', value: 'toda_semana' },
      { label: 'Pelo menos uma vez por mês', value: 'mensal' },
      { label: 'Raramente', value: 'raramente' },
      { label: 'Nunca', value: 'nunca' },
    ],
  },
  {
    id: 'eq_avaliacao_email',
    texto: 'Como você avalia o E-MAIL como ferramenta de trabalho?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    opcoes: [
      { label: 'Ruim', value: 'ruim' },
      { label: 'Regular', value: 'regular' },
      { label: 'Bom', value: 'bom' },
      { label: 'Não uso', value: 'nao_uso' },
    ],
  },
  {
    id: 'eq_avaliacao_whatsapp',
    texto: 'Como você avalia o WHATSAPP como ferramenta de trabalho?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    opcoes: [
      { label: 'Ruim', value: 'ruim' },
      { label: 'Regular', value: 'regular' },
      { label: 'Bom', value: 'bom' },
      { label: 'Não uso', value: 'nao_uso' },
    ],
  },
  {
    id: 'eq_avaliacao_planilhas',
    texto: 'Como você avalia as PLANILHAS como ferramenta de trabalho?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    opcoes: [
      { label: 'Ruim', value: 'ruim' },
      { label: 'Regular', value: 'regular' },
      { label: 'Bom', value: 'bom' },
      { label: 'Não uso', value: 'nao_uso' },
    ],
  },
  {
    id: 'eq_avaliacao_sistema',
    texto: 'Como você avalia o SISTEMA DA EMPRESA como ferramenta de trabalho?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'Ferramentas e Comunicação',
    opcoes: [
      { label: 'Ruim', value: 'ruim' },
      { label: 'Regular', value: 'regular' },
      { label: 'Bom', value: 'bom' },
      { label: 'Não temos sistema', value: 'nao_uso' },
    ],
  },

  // === SEÇÃO C: O QUE MELHORARIA SUA VIDA ===
  {
    id: 'eq_botao_magico',
    texto: 'Se você pudesse resolver UM problema do seu dia a dia com um "botão mágico", qual seria?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'O Que Melhoraria Sua Vida',
    dicaConsultor: 'Essa é a "quick win" para cada pessoa. Resolver isso primeiro gera adesão imediata.',
    opcoes: [
      { label: 'Gerar relatórios automaticamente', value: 'relatorios_auto' },
      { label: 'Ter todas as informações em um lugar só', value: 'centralizar_info' },
      { label: 'Não precisar cobrar colegas sobre tarefas', value: 'sem_cobranca' },
      { label: 'Eliminar preenchimento manual de planilhas', value: 'sem_planilha' },
      { label: 'Ter respostas prontas para perguntas frequentes dos clientes', value: 'faq_clientes' },
    ],
  },
  {
    id: 'eq_requisito_ferramenta',
    texto: 'Se uma ferramenta nova fosse implementada na empresa, o que seria mais importante para você?',
    tipo: 'single',
    obrigatoria: true,
    secao: 'O Que Melhoraria Sua Vida',
    dicaConsultor: 'Define os requisitos não-funcionais da solução. "Simples" + "celular" + "WhatsApp" = arquitetura.',
    opcoes: [
      { label: 'Que seja simples de usar — não quero aprender algo complicado', value: 'simples' },
      { label: 'Que funcione no celular', value: 'celular' },
      { label: 'Que me economize tempo de verdade', value: 'economizar_tempo' },
      { label: 'Que me dê visibilidade do que está acontecendo', value: 'visibilidade' },
      { label: 'Que integre com o que já uso (WhatsApp, e-mail, etc.)', value: 'integracoes' },
    ],
  },
  {
    id: 'eq_dor_principal',
    texto: 'Em uma frase, o que mais atrapalha seu trabalho hoje?',
    tipo: 'text',
    obrigatoria: true,
    secao: 'O Que Melhoraria Sua Vida',
    dicaConsultor: 'Respostas abertas da equipe frequentemente revelam dores que a diretoria desconhece.',
  },
]
